title: Peer Learning
host: 'http://localhost:3001'
port: 3001
paths:
  repo: ./repo
  data: ./data
uploads:
  maxImageFileSize: 3
  maxOtherFileSize: 100
lang: en
langRtl: false
public: true
sessionSecret: 6c7aabcb688287ff1d97c5829d51199f812f8b84ce4be821bde3d3f4ed45b8f6
loginAgentSecret: 'this_secret_must_be_same_as_hku_portal_login_auth_agent'
db: 'mongodb://localhost:27017/peerlearning'
git:
  url: 'git@github.com:hkucsplearn/peer-learning-article.git'
  branch: master
  auth:
    type: ssh
    username: ''
    password: ''
    # for windows
    privateKey: 'C:\Users\Username\.ssh\id_rsa'
    # for linux/macOS
    # '/Users/Username/.ssh/id_rsa'
    sslVerify: true
  showUserEmail: true
  serverEmail: chiholau@connect.hku.hk
  linebreaks: true
  mathjax: true
externalLogging:
  bugsnag: false
  loggly: false
  papertrail: false
  rollbar: false
  sentry: false
theme:
  primary: teal
  alt: blue-grey
  viewSource: all
  footer: blue-grey
  code:
    dark: true
    colorize: true
auth:
  defaultReadAccess: false
  local:
    enabled: true
  hku:
    enabled: true
